import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ArrowDownRight, ArrowUpRight, MoreHorizontal, PencilLine, Trash2, } from "lucide-react";
import { format } from "date-fns";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { getCategoryColor, formatCurrency } from "@/lib/transactions";
function formatTypeLabel(type) {
    return type === "income" ? "Income" : "Expense";
}
export default function TransactionTableRow({ transaction, onEdit, onDelete, canManage, }) {
    const swatch = getCategoryColor(transaction.category);
    const isIncome = transaction.type === "income";
    const TypeIcon = isIncome ? ArrowUpRight : ArrowDownRight;
    return (_jsxs("tr", { className: "border-t border-border/60 transition-colors hover:bg-muted/30", children: [_jsx("td", { className: "px-4 py-4 align-middle text-sm text-muted-foreground", children: format(new Date(transaction.date), "MMM d, yyyy") }), _jsx("td", { className: "px-4 py-4 align-middle", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("span", { className: `flex size-9 shrink-0 items-center justify-center rounded-full ring-1 ring-border/60 ${isIncome
                                ? "bg-emerald-500/15 text-emerald-600"
                                : "bg-rose-500/15 text-rose-600"}`, children: _jsx(TypeIcon, { className: "size-4" }) }), _jsxs("div", { className: "min-w-0", children: [_jsx("div", { className: "truncate font-medium text-foreground", children: transaction.title }), _jsxs("div", { className: "mt-1 flex items-center gap-2 text-xs text-muted-foreground", children: [_jsx("span", { className: "inline-flex items-center rounded-full px-2 py-0.5 font-medium text-background", style: { backgroundColor: swatch }, children: transaction.category }), _jsx("span", { "aria-hidden": "true", children: "-" }), _jsx("span", { children: formatTypeLabel(transaction.type) })] })] })] }) }), _jsx("td", { className: "px-4 py-4 align-middle text-sm text-muted-foreground", children: transaction.category }), _jsx("td", { className: `px-4 py-4 align-middle text-sm font-semibold ${isIncome ? "text-emerald-500" : "text-rose-500"}`, children: formatCurrency(transaction.amount) }), canManage ? (_jsx("td", { className: "px-4 py-4 align-middle", children: _jsxs(DropdownMenu, { children: [_jsx(DropdownMenuTrigger, { className: "inline-flex size-7 items-center justify-center rounded-md border border-transparent bg-transparent text-muted-foreground outline-none transition-colors hover:bg-muted hover:text-foreground focus-visible:border-ring focus-visible:ring-2 focus-visible:ring-ring/30", children: _jsx(MoreHorizontal, { className: "size-4" }) }), _jsxs(DropdownMenuContent, { align: "end", className: "w-44", children: [_jsxs(DropdownMenuItem, { onClick: () => onEdit(transaction), children: [_jsx(PencilLine, { className: "size-3.5" }), "Edit transaction"] }), _jsx(DropdownMenuSeparator, {}), _jsxs(DropdownMenuItem, { variant: "destructive", onClick: () => onDelete(transaction), children: [_jsx(Trash2, { className: "size-3.5" }), "Delete transaction"] })] })] }) })) : null] }));
}
