import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Area, AreaChart, CartesianGrid, Line, ResponsiveContainer, Tooltip, XAxis, YAxis, } from "recharts";
import { Card, CardContent } from "@/components/ui/card";
import { formatCurrency, getMonthlyBalanceSeries } from "@/lib/transactions";
function BalanceTooltip({ active, payload, label }) {
    if (!active || !payload?.length) {
        return null;
    }
    const balance = payload.find((entry) => entry.dataKey === "value")?.value ?? 0;
    const income = payload.find((entry) => entry.dataKey === "income")?.value ?? 0;
    const expenses = payload.find((entry) => entry.dataKey === "expenses")?.value ?? 0;
    return (_jsxs("div", { className: "rounded-xl border border-sidebar-border bg-popover/95 px-3 py-3 text-xs shadow-xl ring-1 ring-border/40 backdrop-blur-md", children: [_jsx("div", { className: "mb-2 font-medium text-popover-foreground", children: label }), _jsxs("div", { className: "grid gap-2 text-muted-foreground", children: [_jsxs("div", { className: "flex items-center justify-between gap-4", children: [_jsxs("span", { className: "flex items-center gap-2", children: [_jsx("span", { className: "size-2.5 rounded-full bg-chart-1" }), "Balance"] }), _jsx("span", { className: "font-medium text-foreground", children: formatCurrency(Number(balance)) })] }), _jsxs("div", { className: "flex items-center justify-between gap-4", children: [_jsxs("span", { className: "flex items-center gap-2", children: [_jsx("span", { className: "size-2.5 rounded-full bg-chart-2" }), "Income"] }), _jsx("span", { className: "font-medium text-chart-2", children: formatCurrency(Number(income)) })] }), _jsxs("div", { className: "flex items-center justify-between gap-4", children: [_jsxs("span", { className: "flex items-center gap-2", children: [_jsx("span", { className: "size-2.5 rounded-full bg-chart-4" }), "Expenses"] }), _jsx("span", { className: "font-medium text-chart-4", children: formatCurrency(Number(expenses)) })] })] })] }));
}
export default function BalanceChart({ transactions }) {
    const data = getMonthlyBalanceSeries(transactions);
    return (_jsx(Card, { className: "h-full", children: _jsxs(CardContent, { className: "p-5", children: [_jsx("h3", { className: "mb-1 font-medium", children: "Balance trend" }), _jsx("p", { className: "mb-4 text-xs text-muted-foreground", children: "Rolling balance based on seeded and user-added transactions." }), _jsx("div", { className: "h-62.5", children: _jsx(ResponsiveContainer, { width: "100%", height: "100%", children: _jsxs(AreaChart, { data: data, children: [_jsx("defs", { children: _jsxs("linearGradient", { id: "balanceFill", x1: "0", y1: "0", x2: "0", y2: "1", children: [_jsx("stop", { offset: "5%", stopColor: "var(--chart-1)", stopOpacity: 0.45 }), _jsx("stop", { offset: "95%", stopColor: "var(--chart-1)", stopOpacity: 0.02 })] }) }), _jsx(CartesianGrid, { strokeDasharray: "3 3", stroke: "var(--border)", opacity: 0.4 }), _jsx(XAxis, { dataKey: "name", stroke: "var(--muted-foreground)" }), _jsx(YAxis, { stroke: "var(--muted-foreground)", tickFormatter: formatCurrency }), _jsx(Tooltip, { content: _jsx(BalanceTooltip, {}) }), _jsx(Area, { type: "monotone", dataKey: "value", stroke: "var(--chart-1)", strokeWidth: 3, fill: "url(#balanceFill)", fillOpacity: 1 }), _jsx(Line, { type: "monotone", dataKey: "income", stroke: "var(--chart-2)", strokeWidth: 2, dot: false }), _jsx(Line, { type: "monotone", dataKey: "expenses", stroke: "var(--chart-4)", strokeWidth: 2, strokeDasharray: "5 5", dot: false })] }) }) })] }) }));
}
